src/api/urls.py
from django.urls import path
from .views import (
    ExpenseListModel,
    IncomeListModel,
    ExpenseAddModel,
    IncomeAddModel,
    ExpenseEditModel,
    IncomeEditModel,
    ExpenseDeleteModel,
    IncomeDeleteModel,
    AccountApi,
    AccountDetailApi,
    ExchangeRateAPIView,
    UserListAPIView,
)


urlpatterns = [
    
    path('account/', AccountApi.as_view(), name="account"),
    path('account/<int:pk>/', AccountDetailApi.as_view(), name="account_detail"),
    path('account/list/', UserListAPIView.as_view(), name="account_list"),
    
    
    path('expenses/', ExpenseListModel.as_view(), name='expense-list'),
    path('incomes/', IncomeListModel.as_view(), name='income-list'),

    path('expenses/add/', ExpenseAddModel.as_view(), name='expense-create'),
    path('incomes/add/', IncomeAddModel.as_view(), name='income-create'),

    path('expenses/<int:pk>/edit/', ExpenseEditModel.as_view(), name='expense-detail-update'),
    path('incomes/<int:pk>/edit/', IncomeEditModel.as_view(), name='income-detail-update'),
    path('expenses/<int:pk>/delete/', ExpenseDeleteModel.as_view(), name='expense-delete'),
    path('incomes/<int:pk>/delete/', IncomeDeleteModel.as_view(), name='income-delete'),
    
    path('exchangerate/', ExchangeRateAPIView.as_view(), name='exchange'),
    
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('account/', include('account.urls')),
    path('api/v1/', include('api.urls')),
    
 
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    
]

src/dashboard/urls.py
from django.urls import path
from . import views
from .views import home
from .views import ExpensesListView, ExpensesCreateView, ExpensesUpdateView, ExpensesDeleteView,IncomeListView, IncomeCreateView, IncomeUpdateView, IncomeDeleteView
app_name = 'dashboard'


urlpatterns = [
    path('home/', home, name='home'),  
    path('expenses/', ExpensesListView.as_view(), name='expenses'), 
    path('expenses/add/', ExpensesCreateView.as_view(), name='add'),
    path('expenses/edit/<int:pk>',ExpensesUpdateView.as_view(), name='edit'),
    path('expenses/delete/<int:pk>',ExpensesDeleteView.as_view(), name='delete'),   
    path('income/', IncomeListView.as_view(), name='income'), 
    path('income/add/', IncomeCreateView.as_view(), name='incomeadd'),
    path('income/edit/<int:pk>',IncomeUpdateView.as_view(), name='incomeedit'),
    path('income/delete/<int:pk>',IncomeDeleteView.as_view(), name='incomedelete'),
]

src/dashboard/models.py
from django.db import models

# Create your models here.

src/dashboard/forms.py
from django import forms
from tracker.models import Expense,Income 

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['spent_amount', 'category', 'date', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Select category'
        self.fields['date'].widget.attrs['type'] = 'date'
        
        
class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ['earned_amount', 'category', 'date', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Select category'
        self.fields['date'].widget.attrs['type'] = 'date'

src/dashboard/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from tracker.models import Expense, Income,ExpenseCategory,IncomeCategory
from .forms import ExpenseForm, IncomeForm

def home(request):
    return render(request, 'dashboard/dashboard.html')

class ExpensesListView(ListView):
    model = Expense
    template_name = 'dashboard/expenses.html'
    context_object_name = 'page_obj'
    paginate_by = 8

    def get_queryset(self):
        return Expense.objects.filter(user=self.request.user)


class ExpensesCreateView(LoginRequiredMixin, CreateView):
    model = Expense
    form_class = ExpenseForm
    template_name = 'dashboard/expensesadd.html'
    success_url = reverse_lazy('dashboard:expenses')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        messages.success(self.request, "New Record Added Successfully")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ExpenseCategory.objects.all()
        return context

class ExpensesUpdateView(LoginRequiredMixin, UpdateView):
    model = Expense
    form_class = ExpenseForm
    template_name = 'dashboard/expensesadd.html'
    success_url = reverse_lazy('dashboard:expenses')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        messages.success(self.request, "Edited Successfully")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edit'] = True
        context['category'] = ExpenseCategory.objects.all()
        return context

class ExpensesDeleteView(LoginRequiredMixin, DeleteView):
    model = Expense
    success_url = reverse_lazy('dashboard:expenses')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Deleted Successfully")
        return super().delete(request, *args, **kwargs)
    

class IncomeListView(ListView):
    model = Income
    template_name = 'dashboard/income.html'
    context_object_name = 'page_obj_2'
    paginate_by = 5

    def get_queryset(self):
        return Expense.objects.filter(user=self.request.user)
    
    

class IncomeCreateView(LoginRequiredMixin, CreateView):
    model = Income
    form_class = IncomeForm
    template_name = 'dashboard/incomeadd.html'
    success_url = reverse_lazy('dashboard:income')
    
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        messages.success(self.request, "New Record Added Successfully")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = IncomeCategory.objects.all()
        return context


class IncomeUpdateView(LoginRequiredMixin, UpdateView):
    model = Income
    form_class = IncomeForm
    template_name = 'dashboard/incomeadd.html'
    success_url = reverse_lazy('dashboard:income')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        messages.success(self.request, "Edited Successfully")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edit'] = True
        context['category'] = IncomeCategory.objects.all()
        return context


class IncomeDeleteView(LoginRequiredMixin, DeleteView):
    model = Expense
    success_url = reverse_lazy('dashboard:income')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Deleted Successfully")
        return super().delete(request, *args, **kwargs)

src/dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard/main.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
<div class="container">

{% if user.is_authenticated %}
          {% comment %} <form method="post" action="{% url 'auth:logout' %}"> {% endcomment %}
            {% csrf_token %}
           <button class="btn btn-md btn-danger" type="submit">Logout</button>
          </form>
          
{% else %}
          {% comment %} <a class="btn btn-md btn-success" href="{% url 'auth:login' %}">Login</a> {% endcomment %}
{% endif %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">About the project</h1>
  </div>
  <ul>
    <li>
      Manage your incomes and expenditures.
    </li>
  </ul>
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">More Features</h1>
  </div>
  <ul>
    <li>
      Export data in csv format.
    </li>
  </ul>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Technologies Used</h1>
</div>
<ul>
  <li>
    Django in backend.
  </li>
  <li>
    Bootstrap, javascript in frontend.
  </li>
  <li>
    Postgresql for database.
  </li> 
</ul>
</div>
{% endblock content %}

src/dashboard/templates/dashboard/expenses.html
{% extends 'dashboard/main.html' %}
{% load static %}
{% block title %}Expenses Section{% endblock title %}
{% block content %}

  <a href="{% url 'dashboard:add' %}"><button type="submit" class="btn btn-success btn-sm mt-1 mb-1" >Add Expenses</button></a>
  <a href="" class="btn btn-danger btn-sm">Export data</a>
  <div class="table-responsive mt-3">
    <table class="table table-lg table-borderless table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Number</th>
          <th scope="col">Amount </th>
          <th scope="col">Description</th>
          <th scope="col">Category</th>
          <th scope="col">Date</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for i in page_obj %}
        <tr>
          <td scope="row">{{ forloop.counter }}</td>
          <td>{{i.spent_amount}}</td>
          <td>{{i.description}}</td>
          <td>{{i.category}}</td>
          <td>{{i.date}}</td>
          <td><a href="{% url 'dashboard:edit' i.pk%}" class="btn btn-sm btn-outline-success">Edit</a>
          <a href="{% url 'dashboard:delete' i.pk %}" class="btn btn-sm btn-outline-danger">Delete</a></td>
        </tr>
        {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>

  <div class="pagination-container">
    <div class="page-item">
        Showing page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </div>

    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
            <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
            <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }} &raquo;</a></li>
        {% endif %}
    </ul>
</div>

  
      <div class="chart">
        <canvas id="myChart" style="height: 50%; width:50%;"></canvas>
      </div>
   
 
      <script src="{% static 'js/stats.js' %}"> </script>
{% endblock %}

src/dashboard/templates/dashboard/expensesadd.html
{% extends 'dashboard/main.html' %}

{% block title %}
{% if edit %}
Edit Expenses
{% else %}
Add New Expenses
{% endif %}
{% endblock title %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      {% if edit %}
      <form class="form" method="post" action="{% url 'dashboard:edit' object.pk%}">
      {% else %}
      <form class="form" method="post" action="">
      {% endif %}
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label">Amount</label>
          <input class="form-control" type="text" name="amount" value="{{ form.amount.value }}">
        </div>  
        <div class="mb-3">
          <label class="form-label">Category</label>
          <select class="form-select form-select-md" name="category">
            <option value="" selected disabled>Choose category</option>
            {% for category in categories %}
            <option value="{{ category.name }}">{{ category.name }}</option>
            {% endfor %}
          </select>
        </div>  
        <div class="mb-3">
          <label class="form-label">Date</label>
          <input class="form-control" type="date" name="date" value="{{ form.date.value }}">
        </div>  
        <div class="mb-3">
          <label class="form-label">Description</label>
          <input class="form-control" type="text" name="description" value="{{ form.description.value }}">
        </div>  
        <input type="submit" class="btn btn-primary" value="{% if edit %}Update{% else %}Add{% endif %}">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

src/dashboard/templates/dashboard/income.html
{% extends 'dashboard/main.html' %}
{% load static %}
{% block title %}Income Section{% endblock title %}
{% block content %}


  <a href="{% url 'dashboard:incomeadd' %}"><button type="submit" class="btn btn-success btn-sm mt-1 mb-1" >Add income</button></a>
  <a href="" class="btn btn-danger btn-sm">Export data</a>
  {% comment %} {% url 'income:export' %} {% endcomment %}
  <div class="table-responsive mt-3">
    <table class="table table-lg table-borderless table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Number</th>
          <th scope="col">Amount</th>
          <th scope="col">Description</th>
          <th scope="col">Category</th>
          <th scope="col">Date</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for i in page_obj_2 %}
        <tr>
          <td scope="row">{{ forloop.counter }}</td>
          <td>{{i.earned_amount}}</td>
          <td>{{i.description}}</td>
          <td>{{i.category}}</td>
          <td>{{i.date}}</td>
          <td><a href="{% url 'dashboard:incomeedit' i.pk %}" class="btn btn-sm btn-outline-success">Edit</a>
          <a href="{% url 'dashboard:incomedelete' i.pk %}" class="btn btn-sm btn-outline-danger">Delete</a></td>
        </tr>
        {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>

  <div class="pagination-container">
    <div class="page-item">
      Showing page {{page_obj_2.number}} of {{ page_obj_2.paginator.num_pages }}
    </div>

    <ul class="pagination justify-content-end">
      {% if page_obj_2.has_previous %}
      <li {% if page_obj_2.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj_2.previous_page_number }}">Previous</a></li>
      {% endif %}

      {% if page_obj_2.has_next %}
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj_2.next_page_number }}">Next</a></li>
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj_2.paginator.num_pages }}">{{ page_obj_2.paginator.num_pages}} &raquo;</a></li>
      {% endif %}

      </ul>
      <div class="chart">
        <canvas id="myChart" style="height: 50%; width:50%;"></canvas>
      </div>
   
 
      <script src="{% static 'js/incomestats.js' %}"> </script>
{% endblock %}

src/dashboard/templates/dashboard/incomeadd.html
{% extends 'dashboard/main.html' %}

{% block title %}
{% if edit %}
Edit Income
{% else %}
Add New Income
{% endif %}
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        {% if edit %}
        <form class="form" method="post" action="{% url 'dashboard:incomeedit' object.pk%}">
        {% else %}
        <form class="form" method="post" action="">
        {% endif %}
          {% csrf_token %}
          <div class="mb-3">
            <label class="form-label">Amount</label>
            <input class="form-control" type="text" name="amount" value="{{ form.amount.value }}">
          </div>  
          <div class="mb-3">
            <label class="form-label">Category</label>
            <select class="form-select form-select-md" name="category">
              <option value="" selected disabled>Choose category</option>
              {% for category in categories %}
              <option value="{{ category.name }}">{{ category.name }}</option>
              {% endfor %}
            </select>
          </div>  
          <div class="mb-3">
            <label class="form-label">Date</label>
            <input class="form-control" type="date" name="date" value="{{ form.date.value }}">
          </div>  
          <div class="mb-3">
            <label class="form-label">Description</label>
            <input class="form-control" type="text" name="description" value="{{ form.description.value }}">
          </div>  
          <input type="submit" class="btn btn-primary" value="{% if edit %}Update{% else %}Add{% endif %}">
        </form>
      </div>
    </div>
  </div>
  {% endblock content %}
  

src/dashboard/templates/dashboard/main.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Finance Tracker</title>

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
<!-- <script src="{% static 'js/index.js' %}"></script> -->
<link rel="stylesheet" href="{% static 'static/css/main.css' %}">
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="{% static 'js/index.js' %}"></script>
<meta name="theme-color" content="#7952b3">
    
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
  </head>
  <body style="color:darkslategray;">
    
    <header class="navbar navbar-dark sticky-top bg-info flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">Tracker</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_authenticated %}
      <p class="text-white h6">Welcome, {{user.username}}</p>
      {% endif %}
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          
          <!-- <a class="nav-link" href="">Logout</a> -->
        </li>
      </ul>
    </header>
    
    <div class="container-fluid">
      <div class="row">
        {% include "dashboard/sider.html" %}
    
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{% block title %}Dashboard{% endblock title %}</h1>
          </div>
          {% if messages %}
          <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="alert alert-lg alert-{{ message.tags }}" {% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
          {% endif %}
            {% block content %}
            
            {% endblock content %}
      </div>
      </main>
      
    </div>

    

  <script src="{% static 'js/min.js' %}"></script>
</body>

</html>

src/dashboard/templates/dashboard/sider.html
{% block var %}
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'dashboard:home' %}">
            <span data-feather="home"></span>
            Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:expenses' %}">
            <span data-feather="shopping-cart"></span>
            Expenses
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:income' %}">
            <span data-feather="dollar-sign"></span>
            Income
          </a>
        </li>
        </li>
      </ul>

      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>Summary</span>
        <!-- <a class="link-secondary" href="#" aria-label="Add a new report">
          <span data-feather="plus-circle"></span>
        </a> -->
      </h6>
      <ul class="nav flex-column mb-2">
        <li class="nav-item">
          {% comment %} <a class="nav-link" href="{% url 'expenses:stat' %}"> {% endcomment %}
            <span data-feather="file-text"></span>
            Expenses Summary
          </a>
        </li>
        <li class="nav-item">
          {% comment %} <a class="nav-link" href="{% url 'income:stat' %}"> {% endcomment %}
            <span data-feather="file-text"></span>
            Income Summary
          </a>
        </li>
        <li class="nav-item">
          {% comment %} <a class="nav-link" href="{% url 'expenses:settings' %}"> {% endcomment %}
            <span data-feather="settings"></span>
            Settings
          </a>
        </li>
      </ul>
    </div>
  </nav>
{% endblock %}

src/dashboard/templates/dashboard/stats.html
{% extends 'dashboard/main.html' %}
{% load static %}
{% block title %}Expenses Statics{% endblock title %}
{% block content %}

<div class="chart">
    <canvas id="myChart2" class="chart-item mt-5"></canvas>
    <canvas id="myChart3" class="chart-item mt-5"></canvas>
</div>
<style>
   
    .chart{
         height:100vh; width:auto;
    }
</style>

 
<script src="{% static 'js/stats.js' %}"> </script>
{% endblock content %}

src/dashboard/templates/dashboard/userpref.html
{% extends 'dashboard/main.html' %}
{% block title %}User Preferences{% endblock title %}
{% block content %}
<div class="container mt-5">
<form method="post" action="{% url 'expenses:settings' %}">
    {% csrf_token %}
<select class="form-select form-select-lg mb-3 mt-5" name='currency'>
    <option selected>{{prev}}</option>
   {% for i in curr %}
    <option value="{{i.value}}">{{i.value}}</option>
   {% endfor %}
</select>
<input type="submit" class="btn btn-primary" />
</div>
</form>
{% endblock %}